// Generated by LiveScript 1.4.0
(function(){
  var _, Backbone, idsclient;
  _ = require('underscore');
  Backbone = require('backbone4000');
  idsclient = require('idsclient').idsclient;
  exports.lego = backbone.Model.extend4000({
    init: function(callback){
      var idsclient;
      idsclient = this.idsclient = this.env.idsclient = new idsclient(this.settings);
      this.env.ids = idsClient.send;
      return callback();
    }
  });
}).call(this);
